### ISSUE TITLE
(Suggestion) Adjust the crafting shape of scarves.

### ISSUE THREAD

**Issue by laserlemons** [MehVahdJukaar/Christmas#2]
I suggest changing the scarf recipe to this shape to avoid conflicts with other mods:

x x x
W W x     W = Wool
x  x W

An example of a mod that has a conflict is the sleeping bags from the Comforts mod.

**Comment by MehVahdJukaar** [comment]
This mod doesn't add any scarf

**Comment by laserlemons** [comment]
Well this is embarrassing. I meant to post this one on Winter Overhaul.
