### ISSUE TITLE
sleds slow on thick snow

### ISSUE THREAD

**Issue by ryleu** [MehVahdJukaar/Christmas#66]
on snow layers thicker than 1, sleds are very slow

**Comment by MehVahdJukaar** [comment]
i cant replicate. testd on 1.20, forge

**Comment by ryleu** [comment]
i'm on 1.20.1 fabric... not sure if that makes a difference

**Comment by MehVahdJukaar** [comment]
tested on that too, cant replicate

**Comment by ryleu** [comment]
odd, maybe there was some other factor. i'll close the issue
