### ISSUE TITLE
New update for forge 1.20.1 doesn't let the game start

### ISSUE THREAD

**Issue by vinnyg0621** [MehVahdJukaar/Christmas#88]
all I could find in the log was "mixin apply for snowyspirit failed"
https://paste.gg/p/anonymous/c98e9ec18f6d4505b85d7e1f243371b4

**Comment by Klouver-github** [comment]
I can confirm this is happening to me when I have Entity Model Features mod installed

**Comment by Klouver-github** [comment]
thank you for updating Snowy Spirit so it works with EMF
