### ISSUE TITLE
Glow Lights cannot be placed on Dynamic Trees leaves

### ISSUE THREAD

**Issue by apatheticAccismus** [MehVahdJukaar/Christmas#91]
Testing environment:
`Minecraft 1.20.1`
`Forge - 47.3.12`
`snowyspirit-1.20-3.0.9`
`DynamicTrees-1.20.1-1.3.4`

Title. Having read #62 I assumed the issue was due to the fact that Dynamic Trees also makes leaves blocks semi-passable. However, disabling the semi-passable leaves feature in Dynamic Trees' server config file does not fix the issue.

I also thought the issue might be that dynamic trees leaves may not be tagged as leaves blocks. Curiously, trying to add `#dynamictrees:leaves` or any block such as `dynamictrees:oak_leaves` to the `#minecraft:leaves` tag using KubeJS results in no blocks being added to the tag. For some reason, `dynamictrees:oak_leaves` doesn't exist as a block, despite that being the identifier for the block when it's placed in the world. May have to do with the fact that using the Pick Block function in creative mode on dynamic trees leaves instead gives vanilla leaves blocks.

I'm assuming it would be best if the issue was handled on Snowy Spirit's side, which is why I've posted the issue here.

**Comment by MehVahdJukaar** [comment]
well the reason for this is that i am checking if the target block has full block collision to be valid as glow light themselves do have full collision

**Comment by apatheticAccismus** [comment]
Then there shouldn't be any issue when I disable the passable leaves setting in Dynamic Trees' config file. But when I do disable this setting and make leaves have full block collision, I still can't place glow lights on the leaves.

**Comment by MehVahdJukaar** [comment]
try new version

**Comment by MehVahdJukaar** [comment]
leaves still need to be tagged as minecraft:leaves of course

**Comment by apatheticAccismus** [comment]
Yup, works perfectly now. Thanks a bunch.
