### ISSUE TITLE
Latest ver. of snowy spirit 1.21.1 neoforge

### ISSUE THREAD

**Issue by TheeMrCheeky** [MehVahdJukaar/Christmas#94]
[crash-2024-11-22_08.41.09-client.txt](https://github.com/user-attachments/files/17871224/crash-2024-11-22_08.41.09-client.txt)

**Comment by MehVahdJukaar** [comment]
try new version

**Comment by TheeMrCheeky** [comment]
no go as soon as I install it an as its loading into main menu from loading mods screen , during the mojang studio loading bar it crashes with snowy installed 
[crash-2024-11-22_18.31.56-client.txt](https://github.com/user-attachments/files/17877496/crash-2024-11-22_18.31.56-client.txt)

**Comment by MehVahdJukaar** [comment]
You sure it's snowy spirit? I just see an error from additional structures. Plus it complains about a config not being loaded but I even early load both of mine

**Comment by TheeMrCheeky** [comment]
I mean I can't say it is for sure due to your mod (could be a incompatibility , only happens with snowy installed once I delete snowy it no longer crashes

**Comment by MehVahdJukaar** [comment]
well did you try without that mod?

**Comment by TheeMrCheeky** [comment]
![image](https://github.com/user-attachments/assets/c7e0cfdc-e8ea-4c57-a809-822aa52c4e51)

with out additional structures I make it to this screen now

**Comment by chriskeena** [comment]
I just updated to 1.21.1-3.0.13 and get a similar error message about a compatibility mod that can't be found.
https://mclo.gs/OogXPGk

**Comment by TheeMrCheeky** [comment]
HEY idk if it was the new moonlight update or snowy but it works now!!
